import type { McfError } from '../types/common.js';

export function mcfError(
  command: string,
  errorCode: string,
  message: string,
  context: Record<string, unknown> = {},
): McfError {
  return { ok: false, command, error_code: errorCode, message, context };
}

// Error code constants
export const ERR = {
  // General
  NOT_GIT_REPO: 'NOT_GIT_REPO',
  DB_EXISTS: 'DB_EXISTS',
  NO_DB: 'NO_DB',
  DB_ERROR: 'DB_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DB_CONTENTION: 'DB_CONTENTION',

  // Feature
  DUPLICATE_FEATURE: 'DUPLICATE_FEATURE',
  FEATURE_NOT_FOUND: 'FEATURE_NOT_FOUND',
  FEATURE_NOT_APPROVED: 'FEATURE_NOT_APPROVED',
  INVALID_ID: 'INVALID_ID',
  NO_CRITERIA: 'NO_CRITERIA',

  // Packet
  DUPLICATE_PACKET: 'DUPLICATE_PACKET',
  PACKET_NOT_FOUND: 'PACKET_NOT_FOUND',
  PACKET_NOT_READY: 'PACKET_NOT_READY',
  PACKET_NOT_CLAIMED: 'PACKET_NOT_CLAIMED',
  PACKET_NOT_IN_PROGRESS: 'PACKET_NOT_IN_PROGRESS',
  PACKET_NOT_SUBMITTED: 'PACKET_NOT_SUBMITTED',
  INVALID_PACKET_ID: 'INVALID_PACKET_ID',
  FILE_OVERLAP: 'FILE_OVERLAP',
  DEPENDENCY_NOT_FOUND: 'DEPENDENCY_NOT_FOUND',
  CIRCULAR_DEPENDENCY: 'CIRCULAR_DEPENDENCY',
  MISSING_MERGE_LAYER: 'MISSING_MERGE_LAYER',
  ROLE_ACCESS_VIOLATION: 'ROLE_ACCESS_VIOLATION',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  INCOMPLETE_PACKET: 'INCOMPLETE_PACKET',

  // State
  INVALID_STATE: 'INVALID_STATE',
  TERMINAL_STATE: 'TERMINAL_STATE',
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION',

  // Claim
  DEPENDENCIES_NOT_MET: 'DEPENDENCIES_NOT_MET',
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',
  ROLE_CONFLICT: 'ROLE_CONFLICT',
  CLAIM_NOT_FOUND: 'CLAIM_NOT_FOUND',
  CLAIM_NOT_ACTIVE: 'CLAIM_NOT_ACTIVE',
  NOT_OWNER: 'NOT_OWNER',
  MAX_RENEWALS: 'MAX_RENEWALS',
  CLAIM_EXPIRED: 'CLAIM_EXPIRED',

  // Submit
  INVALID_ARTIFACTS: 'INVALID_ARTIFACTS',
  INVALID_WRITEBACK: 'INVALID_WRITEBACK',
  FORBIDDEN_FILE_TOUCHED: 'FORBIDDEN_FILE_TOUCHED',
  PROTECTED_FILE_VIOLATION: 'PROTECTED_FILE_VIOLATION',
  SEAM_FILE_VIOLATION: 'SEAM_FILE_VIOLATION',
  SCOPE_VIOLATION: 'SCOPE_VIOLATION',
  NO_TESTS: 'NO_TESTS',
  DELTA_NOT_FOUND: 'DELTA_NOT_FOUND',
  MERGE_READINESS_MISSING: 'MERGE_READINESS_MISSING',

  // Verify
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  INDEPENDENCE_VIOLATION: 'INDEPENDENCE_VIOLATION',
  CHECKLIST_REQUIRED_FIRST: 'CHECKLIST_REQUIRED_FIRST',
  INVALID_CHECKS: 'INVALID_CHECKS',
  VERDICT_MISMATCH: 'VERDICT_MISMATCH',
  MISSING_FAILURES: 'MISSING_FAILURES',
  MISSING_ANALYSIS: 'MISSING_ANALYSIS',

  // Approve
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',
  TYPE_MISMATCH: 'TYPE_MISMATCH',
  CONDITIONS_REQUIRED: 'CONDITIONS_REQUIRED',

  // Integrate
  PACKETS_NOT_READY: 'PACKETS_NOT_READY',
  MISSING_PROMOTIONS: 'MISSING_PROMOTIONS',
  MISSING_APPROVALS: 'MISSING_APPROVALS',
  NO_MERGE_APPROVAL: 'NO_MERGE_APPROVAL',
  TARGET_MISMATCH: 'TARGET_MISMATCH',
  INVALID_RUN_STATE: 'INVALID_RUN_STATE',
  VERIFICATION_NOT_PASSED: 'VERIFICATION_NOT_PASSED',

  // Promote
  ALREADY_PROMOTED: 'ALREADY_PROMOTED',
} as const;
